/**
 * myPilotPost — Report Components
 * All return HTML strings. No React. No PDF libraries.
 * SVG charts only — no canvas.
 */

// ── Utilities ───────────────────────────────────────────────────────────────

export function esc(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function SC(score) {
  return score >= 70 ? 'var(--score-strong)' : score >= 50 ? 'var(--score-developing)' : 'var(--score-weak)';
}

export function SL(score) {
  return score >= 70 ? 'Strong' : score >= 50 ? 'Developing' : 'Needs Work';
}

function safeList(items, cls = '') {
  if (!items?.length) return '<li class="na-item">No data available</li>';
  return items.map(s => `<li${cls ? ` class="${cls}"` : ''}>${esc(s)}</li>`).join('');
}

function keyLabel(key) {
  return key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

// ── SVG Primitives ──────────────────────────────────────────────────────────

function renderDonut(score, color, size = 160, strokeWidth = 14) {
  const cx = size / 2;
  const cy = size / 2;
  const r = cx - strokeWidth / 2 - 4;
  const circ = +(2 * Math.PI * r).toFixed(2);
  const filled = +(circ * (score / 100)).toFixed(2);
  const gap = +(circ - filled).toFixed(2);
  const fs = Math.round(size * 0.225);
  const sub = Math.round(size * 0.088);
  return `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" aria-label="Score ${score}/100">
  <circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#e8edf5" stroke-width="${strokeWidth}"/>
  <circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${color}" stroke-width="${strokeWidth}"
    stroke-dasharray="${filled} ${gap}" stroke-linecap="round"
    transform="rotate(-90 ${cx} ${cy})"/>
  <text x="${cx}" y="${cy - 5}" text-anchor="middle"
    font-size="${fs}" font-weight="900" fill="${color}"
    font-family="'Inter',-apple-system,BlinkMacSystemFont,sans-serif">${score}</text>
  <text x="${cx}" y="${cy + sub + 4}" text-anchor="middle"
    font-size="${sub}" fill="#94a3b8" font-weight="700"
    font-family="'Inter',-apple-system,BlinkMacSystemFont,sans-serif">/100</text>
</svg>`;
}

function renderSvgBar(value, color, trackW = 180, h = 8) {
  const fw = Math.max(0, Math.min(100, value)) / 100 * trackW;
  return `<svg width="${trackW}" height="${h}" viewBox="0 0 ${trackW} ${h}" style="display:block;flex-shrink:0">
  <rect x="0" y="0" width="${trackW}" height="${h}" rx="${h / 2}" fill="#f1f5f9"/>
  <rect x="0" y="0" width="${fw.toFixed(1)}" height="${h}" rx="${h / 2}" fill="${color}"/>
</svg>`;
}

function renderMixBar(mix, width = 360) {
  const COLORS = ['#2563eb','#10b981','#f59e0b','#7c3aed','#ef4444','#06b6d4','#84cc16'];
  const entries = Object.entries(mix || {}).filter(([, v]) => v > 0);
  if (!entries.length) return '';
  let x = 0;
  const bars = entries.map(([, v], i) => {
    const bw = +(v / 100 * width).toFixed(2);
    const bar = `<rect x="${x.toFixed(2)}" y="0" width="${bw}" height="20" fill="${COLORS[i % COLORS.length]}"/>`;
    x += bw;
    return bar;
  }).join('');
  const legend = entries.map(([k, v], i) =>
    `<div class="mix-leg-item"><span class="mix-dot" style="background:${COLORS[i % COLORS.length]}"></span><span class="mix-lbl">${esc(keyLabel(k))}</span><span class="mix-pct">${v}%</span></div>`
  ).join('');
  return `<div class="mix-chart-wrap">
    <svg width="${width}" height="20" viewBox="0 0 ${width} 20" style="border-radius:4px;overflow:hidden;display:block">${bars}</svg>
    <div class="mix-legend">${legend}</div>
  </div>`;
}

// ── renderCover ─────────────────────────────────────────────────────────────

export function renderCover(cover, branding) {
  const { score, scoreColor, scoreLabel, brandName, reportTitle, industry, niche, websiteUrl, date, reportId, dimensions } = cover;
  const donut = renderDonut(score, scoreColor, 180, 16);

  const dimBars = Object.entries(dimensions || {}).slice(0, 5).map(([k, v]) => {
    const c = SC(v);
    return `<div class="cover-dim-row">
      <span class="cover-dim-label">${esc(keyLabel(k))}</span>
      ${renderSvgBar(v, c, 140, 6)}
      <span class="cover-dim-val" style="color:${c}">${v}</span>
    </div>`;
  }).join('');

  const footerLogo = branding.showMypilotpost
    ? `<span class="cover-footer-logo">myPilotPost</span>`
    : `<span class="cover-footer-logo">${esc(branding.clientName || 'Brand Report')}</span>`;

  const attribution = branding.showMypilotpost
    ? 'Generated by myPilotPost'
    : `Prepared for ${esc(branding.clientName || '')}`;

  return `<div class="report-cover" id="cover">
  <div class="cover-top-bar">
    ${branding.showMypilotpost
      ? `<div class="cover-logo-mark">my<span>Pilot</span>Post</div>`
      : `<div class="cover-logo-mark">${esc(branding.clientName || '')}</div>`}
    <div class="cover-type-badge">Brand Intelligence Report</div>
  </div>

  <div class="cover-hero">
    <div class="cover-score-col">
      <div class="cover-donut-wrap">${donut}</div>
      <div class="cover-score-pill" style="background:${scoreColor}22;color:${scoreColor};border-color:${scoreColor}44">${esc(scoreLabel)}</div>
    </div>
    <div class="cover-info-col">
      <div class="cover-report-eyebrow">${esc(reportTitle)}</div>
      <div class="cover-brand-name">${esc(brandName)}</div>
      ${industry ? `<div class="cover-industry">${esc(industry)}${niche ? ` &middot; ${esc(niche)}` : ''}</div>` : ''}
      ${websiteUrl ? `<div class="cover-website">${esc(websiteUrl)}</div>` : ''}
    </div>
  </div>

  ${dimBars ? `<div class="cover-dims-strip">
    <div class="cover-dims-label">Score Dimensions</div>
    <div class="cover-dims-bars">${dimBars}</div>
  </div>` : ''}

  <div class="cover-footer-bar">
    <div class="cover-footer-left">
      ${footerLogo}
      <span class="cover-footer-attribution">${attribution}</span>
    </div>
    <div class="cover-footer-right">
      <span class="cover-footer-date">${esc(date)}</span>
      ${reportId ? `<span class="cover-footer-id">ID: ${esc(reportId)}</span>` : ''}
    </div>
  </div>
</div>`;
}

// ── renderScoreHero ─────────────────────────────────────────────────────────

export function renderScoreHero(data) {
  const { score, dimensions, rationale, label } = data;
  const col = SC(score);

  const dimRows = Object.entries(dimensions || {}).map(([k, v]) => {
    const c = SC(v);
    return `<div class="dim-row">
      <span class="dim-label">${esc(keyLabel(k))}</span>
      <div class="dim-bar-wrap">${renderSvgBar(v, c, 200, 8)}</div>
      <span class="dim-val" style="color:${c}">${v}</span>
    </div>`;
  }).join('');

  return `<div class="score-hero break-avoid">
  <div class="score-donut-col">
    ${renderDonut(score, col, 140, 13)}
    <div class="score-label-pill" style="background:${col}18;color:${col};border-color:${col}33">${esc(label || SL(score))}</div>
  </div>
  <div class="score-detail-col">
    ${rationale ? `<p class="score-rationale">${esc(rationale)}</p>` : ''}
    <div class="dim-bars-group">${dimRows}</div>
  </div>
</div>`;
}

// ── renderSection (wrapper) ─────────────────────────────────────────────────

export function renderSection(section) {
  const num = String(section.number).padStart(2, '0');
  const breakClass = section.pageBreakBefore ? ' section-break-before' : '';

  return `<div class="report-section${breakClass}" id="s${section.number}">
  <div class="section-header">
    <div class="section-watermark" aria-hidden="true">${num}</div>
    <div class="section-meta">
      <span class="section-num-pill">${num}</span>
      <h2 class="section-title-text">${esc(section.title)}</h2>
    </div>
    <div class="section-rule"></div>
  </div>
  <div class="section-body">
    ${section.html}
  </div>
</div>`;
}

// ── renderScore (full score section body) ───────────────────────────────────

export function renderScore(data) {
  return renderScoreHero(data);
}

// ── renderChart (SVG grouped bar chart) ─────────────────────────────────────

export function renderChart(entries, title = '') {
  if (!entries?.length) return '';
  const COLORS = ['#2563eb','#10b981','#f59e0b','#7c3aed','#ef4444'];
  const barW = 28;
  const gap = 14;
  const maxH = 80;
  const svgW = entries.length * (barW + gap) + gap;
  const maxVal = Math.max(...entries.map(e => e.value), 1);

  const bars = entries.map((e, i) => {
    const bh = Math.round((e.value / maxVal) * maxH);
    const x = gap + i * (barW + gap);
    const y = maxH - bh + 16;
    const c = COLORS[i % COLORS.length];
    const label = e.label.length > 8 ? e.label.slice(0, 7) + '…' : e.label;
    return `<rect x="${x}" y="${y}" width="${barW}" height="${bh}" rx="3" fill="${c}"/>
<text x="${x + barW / 2}" y="${y - 4}" text-anchor="middle" font-size="9" fill="${c}" font-weight="700">${e.value}</text>
<text x="${x + barW / 2}" y="${maxH + 26}" text-anchor="middle" font-size="9" fill="#64748b">${esc(label)}</text>`;
  }).join('');

  return `<div class="chart-wrap break-avoid">
  ${title ? `<div class="chart-title">${esc(title)}</div>` : ''}
  <svg width="${svgW}" height="${maxH + 36}" viewBox="0 0 ${svgW} ${maxH + 36}">
    ${bars}
  </svg>
</div>`;
}

// ── renderRoadmap ────────────────────────────────────────────────────────────

export function renderRoadmap(data) {
  const COLS = [
    { key: 'quick_wins', label: 'Quick Wins', time: '0–7 days', color: 'var(--score-strong)', hdrCls: 'rm-hdr-green' },
    { key: 'growth_plays', label: 'Growth Plays', time: '30 days', color: 'var(--pilot-blue)', hdrCls: 'rm-hdr-blue' },
    { key: 'strategic_investments', label: 'Strategic Investments', time: '60–90 days', color: 'var(--purple)', hdrCls: 'rm-hdr-purple' },
  ];

  const cols = COLS.map(col => {
    const items = data[col.key] || [];
    const cards = items.length
      ? items.map(item => `<div class="rm-card" style="border-left-color:${col.color}">
          <div class="rm-action">${esc(item.action)}</div>
          ${item.business_impact ? `<div class="rm-impact">${esc(item.business_impact)}</div>` : ''}
          ${item.expected_outcome ? `<div class="rm-outcome">${esc(item.expected_outcome)}</div>` : ''}
          ${item.timeframe ? `<div class="rm-timeframe">${esc(item.timeframe)}</div>` : ''}
        </div>`).join('')
      : '<p class="na-text" style="padding:12px 14px">None identified.</p>';

    return `<div class="roadmap-col break-avoid">
      <div class="roadmap-col-hdr ${col.hdrCls}">
        <span>${esc(col.label)}</span>
        <span class="rm-time-badge">${col.time}</span>
      </div>
      <div class="roadmap-col-body">${cards}</div>
    </div>`;
  }).join('');

  return `<div class="roadmap-grid">${cols}</div>`;
}

// ── renderCTA ────────────────────────────────────────────────────────────────

export function renderCTA(data, branding) {
  const wa = data.what_becomes_available || {};
  const features = [
    ['Audience Analytics', wa.audience_analytics],
    ['Engagement Analytics', wa.engagement_analytics],
    ['Content Analytics', wa.content_analytics],
    ['Search Console', wa.search_console],
    ['Growth Tracking', wa.growth_tracking],
  ].filter(([, v]) => v);

  const grid = features.map(([title, desc]) =>
    `<div class="cta-item">
      <strong class="cta-item-title">${esc(title)}</strong>
      <span class="cta-item-desc">${esc(desc)}</span>
    </div>`
  ).join('');

  const ctaUrl = branding.showMypilotpost ? 'mypilotpost.com' : (branding.clientUrl || 'mypilotpost.com');

  return `<div class="cta-inner">
  ${data.current_limitations ? `<p class="cta-intro">${esc(data.current_limitations)}</p>` : ''}
  ${data.value_proposition ? `<blockquote class="cta-vp">&ldquo;${esc(data.value_proposition)}&rdquo;</blockquote>` : ''}
  ${grid ? `<div class="cta-grid break-avoid">${grid}</div>` : ''}
  <div class="cta-action-box">
    <strong>Get Started:</strong> Visit <span class="cta-url">${esc(ctaUrl)}</span> to transform this audit into a live, verified brand intelligence dashboard.
  </div>
</div>`;
}

// ── renderBackpage ───────────────────────────────────────────────────────────

export function renderBackpage(backpage, branding) {
  const steps = (backpage.nextActions || [
    'Connect your social accounts for live data tracking',
    'Schedule a monthly brand audit review',
    'Explore AI Content Studio for strategic content',
  ]).slice(0, 4);

  const stepsList = steps.map(s =>
    `<div class="bp-step"><span class="bp-step-dot"></span><span class="bp-step-text">${esc(s)}</span></div>`
  ).join('');

  const qr = `<svg width="88" height="88" viewBox="0 0 88 88" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="QR code for mypilotpost.com">
  <rect width="88" height="88" rx="6" fill="white"/>
  <!-- Position squares -->
  <rect x="4" y="4" width="24" height="24" rx="3" fill="none" stroke="#0f172a" stroke-width="2.5"/>
  <rect x="9" y="9" width="14" height="14" rx="1" fill="#0f172a"/>
  <rect x="60" y="4" width="24" height="24" rx="3" fill="none" stroke="#0f172a" stroke-width="2.5"/>
  <rect x="65" y="9" width="14" height="14" rx="1" fill="#0f172a"/>
  <rect x="4" y="60" width="24" height="24" rx="3" fill="none" stroke="#0f172a" stroke-width="2.5"/>
  <rect x="9" y="65" width="14" height="14" rx="1" fill="#0f172a"/>
  <!-- Data modules -->
  <rect x="34" y="4" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="42" y="4" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="50" y="4" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="34" y="12" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="50" y="12" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="34" y="20" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="42" y="20" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="4" y="34" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="12" y="34" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="20" y="42" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="34" y="34" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="42" y="42" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="50" y="34" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="58" y="42" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="34" y="50" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="50" y="50" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="66" y="34" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="74" y="34" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="66" y="50" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="34" y="66" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="42" y="58" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="50" y="66" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="58" y="58" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="66" y="66" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="74" y="58" width="5" height="5" fill="#0f172a" rx="0.5"/>
  <rect x="74" y="74" width="5" height="5" fill="#0f172a" rx="0.5"/>
</svg>`;

  const showCredit = branding.showMypilotpost;

  return `<div class="report-backpage" id="backpage">
  <div class="bp-inner">
    <div class="bp-top">
      <div class="bp-logo-mark">${showCredit ? 'my<span class="bp-logo-accent">Pilot</span>Post' : esc(branding.clientName || '')}</div>
      <div class="bp-tagline">Brand Intelligence Platform</div>
      <div class="bp-divider"></div>
    </div>

    <div class="bp-content">
      <div class="bp-left">
        <div class="bp-thank-you">Thank you, <strong>${esc(backpage.brandName || '')}</strong></div>
        <div class="bp-next-label">YOUR NEXT STEPS</div>
        <div class="bp-steps">${stepsList}</div>
      </div>
      <div class="bp-right">
        <div class="bp-qr-wrap">
          ${qr}
          <div class="bp-qr-caption">Scan to activate<br>live brand intelligence</div>
        </div>
      </div>
    </div>

    <div class="bp-footer">
      <div class="bp-footer-url">${showCredit ? 'www.mypilotpost.com' : (branding.clientUrl || 'www.mypilotpost.com')}</div>
      <div class="bp-footer-rule"></div>
      <div class="bp-footer-meta">
        ${showCredit ? '<span>Built with myPilotPost</span>' : '<span>Prepared by Brand Intelligence</span>'}
        <span class="bp-footer-dot">&middot;</span>
        <span>${esc(backpage.date || '')}</span>
        ${backpage.reportId ? `<span class="bp-footer-dot">&middot;</span><span>ID&nbsp;${esc(backpage.reportId)}</span>` : ''}
      </div>
    </div>
  </div>
</div>`;
}

// ── Section-specific renderers ───────────────────────────────────────────────

export function renderBusinessProfile(bp) {
  const rows = [
    ['Business Model', bp.business_model],
    ['Target Audience', bp.target_audience],
    ['Primary Offer', bp.primary_offer],
    ['Geographic Market', bp.geographic_market],
    ['Other Offers', bp.secondary_offers?.length ? bp.secondary_offers.map(esc).join(', ') : null],
    ['Confidence', bp.confidence],
  ].filter(([, v]) => v);

  const half = Math.ceil(rows.length / 2);
  const col1 = rows.slice(0, half);
  const col2 = rows.slice(half);

  const makeCol = items => items.map(([k, v]) =>
    `<div class="kv-row"><span class="kv-key">${esc(k)}</span><span class="kv-val">${esc(v)}</span></div>`
  ).join('');

  return `<div class="kv-grid r-grid-2 break-avoid">
  <div class="kv-col">${makeCol(col1)}</div>
  <div class="kv-col">${makeCol(col2)}</div>
</div>
${bp.evidence ? `<div class="callout-box callout-slate">Evidence: ${esc(bp.evidence)}</div>` : ''}`;
}

export function renderDiagnosticSnapshot(ds) {
  return `${ds.executive_summary ? `<div class="callout-box callout-surface summary-box">${esc(ds.executive_summary)}</div>` : ''}
${ds.brand_positioning_assessment ? `<div class="callout-box callout-blue">${esc(ds.brand_positioning_assessment)}</div>` : ''}
<div class="r-grid-2" style="margin-top:16px">
  <div class="r-card r-card--green break-avoid">
    <div class="r-card-label">Strategic Strengths</div>
    <ul class="r-card-list">${safeList(ds.strategic_strengths)}</ul>
  </div>
  <div class="r-card r-card--amber break-avoid">
    <div class="r-card-label">Strategic Weaknesses</div>
    <ul class="r-card-list">${safeList(ds.strategic_weaknesses)}</ul>
  </div>
  <div class="r-card r-card--red break-avoid">
    <div class="r-card-label">Strategic Risks</div>
    <ul class="r-card-list">${safeList(ds.strategic_risks)}</ul>
  </div>
  <div class="r-card r-card--purple break-avoid">
    <div class="r-card-label">Growth Opportunities</div>
    <ul class="r-card-list">${safeList(ds.growth_opportunities)}</ul>
  </div>
</div>`;
}

export function renderSocialPresence(spr) {
  const platforms = (spr.platforms_found || []).map(p => {
    const statusColor = p.status === 'active' ? 'var(--score-strong)' : p.status === 'inactive' ? 'var(--score-developing)' : '#94a3b8';
    const statusBg = p.status === 'active' ? 'rgba(22,163,74,0.08)' : p.status === 'inactive' ? 'rgba(217,119,6,0.08)' : '#f1f5f9';
    const urlEl = p.url && p.url !== 'not found'
      ? `<a href="${esc(p.url)}" target="_blank" class="plat-url">${esc(p.url)}</a>`
      : '<span class="na-text">not found</span>';
    return `<div class="plat-card break-avoid">
      <div class="plat-card-top">
        <span class="plat-name">${esc(p.platform || '')}</span>
        <span class="plat-badge" style="color:${statusColor};background:${statusBg};border-color:${statusColor}33">${esc(p.status || 'unknown')}</span>
      </div>
      <div class="plat-card-url">${urlEl}</div>
      ${p.notes ? `<div class="plat-card-notes">${esc(p.notes)}</div>` : ''}
    </div>`;
  }).join('');

  return `${platforms ? `<div class="platform-cards-grid">${platforms}</div>` : '<p class="na-text">No platform data available.</p>'}
${spr.profile_quality_review ? `<p class="body-text" style="margin-top:14px">${esc(spr.profile_quality_review)}</p>` : ''}
${spr.bio_review ? `<div class="callout-box callout-slate" style="margin-top:10px"><strong>Bio Review:</strong> ${esc(spr.bio_review)}</div>` : ''}
${spr.platforms_missing?.length ? `<div class="callout-box callout-amber" style="margin-top:12px"><strong>Missing Platforms:</strong><ul class="r-card-list" style="margin-top:8px">${safeList(spr.platforms_missing)}</ul></div>` : ''}
${spr.platform_opportunities?.length ? `<div style="margin-top:12px"><div class="eyebrow" style="margin-bottom:8px">Platform Opportunities</div><ul class="r-card-list inline-list">${safeList(spr.platform_opportunities)}</ul></div>` : ''}`;
}

export function renderBrandIdentity(bir) {
  const items = [
    ['Logo Assessment', bir.logo_assessment],
    ['Colour Consistency', bir.colour_consistency],
    ['Typography', bir.typography_consistency],
    ['Visual Consistency', bir.visual_identity_consistency],
  ].filter(([, v]) => v);

  const cards = items.map(([k, v]) =>
    `<div class="r-card r-card--plain break-avoid"><div class="r-card-label">${esc(k)}</div><div class="r-card-val">${esc(v)}</div></div>`
  ).join('');

  return `<div class="r-grid-2">${cards}</div>
${bir.trust_signal_assessment ? `<div class="callout-box callout-slate" style="margin-top:12px"><strong>Trust Signals:</strong> ${esc(bir.trust_signal_assessment)}</div>` : ''}`;
}

export function renderContentGenome(cga) {
  const mixHtml = renderMixBar(cga.estimated_content_mix);
  return `${cga.mix_basis ? `<p class="eyebrow-note">${esc(cga.mix_basis)}</p>` : ''}
${mixHtml}
${cga.content_observations ? `<div class="callout-box callout-surface" style="margin-top:14px">${esc(cga.content_observations)}</div>` : ''}
<div style="margin-top:16px;display:flex;flex-wrap:wrap;gap:20px">
  ${cga.strongest_themes?.length ? `<div><div class="eyebrow" style="color:var(--score-strong);margin-bottom:6px">Strongest Themes</div><div class="theme-pills">${cga.strongest_themes.map(t => `<span class="theme-pill tp-green">${esc(t)}</span>`).join('')}</div></div>` : ''}
  ${cga.weakest_themes?.length ? `<div><div class="eyebrow" style="color:var(--score-developing);margin-bottom:6px">Weakest Themes</div><div class="theme-pills">${cga.weakest_themes.map(t => `<span class="theme-pill tp-amber">${esc(t)}</span>`).join('')}</div></div>` : ''}
  ${cga.missing_themes?.length ? `<div><div class="eyebrow" style="color:var(--score-weak);margin-bottom:6px">Missing Themes</div><div class="theme-pills">${cga.missing_themes.map(t => `<span class="theme-pill tp-red">${esc(t)}</span>`).join('')}</div></div>` : ''}
</div>`;
}

export function renderAudienceResonance(arr) {
  const cards = [
    ['Audience Alignment', arr.audience_alignment],
    ['Messaging Effectiveness', arr.messaging_effectiveness],
    ['Value Proposition', arr.value_proposition_assessment],
  ].filter(([, v]) => v).map(([k, v]) =>
    `<div class="r-card r-card--plain break-avoid"><div class="r-card-label">${esc(k)}</div><div class="r-card-val">${esc(v)}</div></div>`
  ).join('');

  return `<div class="r-grid-3">${cards}</div>
${arr.trust_building_opportunities?.length ? `<div style="margin-top:16px"><div class="eyebrow" style="margin-bottom:8px">Trust-Building Opportunities</div><ul class="r-card-list inline-list">${safeList(arr.trust_building_opportunities)}</ul></div>` : ''}`;
}

export function renderCompetitiveMoat(cmm) {
  const gaps = [
    { key: 'positioning_overlaps', label: 'Positioning Overlaps', cls: 'r-card--blue', items: cmm.positioning_overlaps },
    { key: 'authority_gaps', label: 'Authority Gaps', cls: 'r-card--amber', items: cmm.authority_gaps },
    { key: 'content_gaps', label: 'Content Gaps', cls: 'r-card--red', items: cmm.content_gaps },
    { key: 'whitespace_opportunities', label: 'Whitespace Opportunities', cls: 'r-card--purple', items: cmm.whitespace_opportunities },
  ].filter(g => g.items?.length);

  const cards = gaps.map(g =>
    `<div class="r-card ${g.cls} break-avoid"><div class="r-card-label">${esc(g.label)}</div><ul class="r-card-list">${safeList(g.items)}</ul></div>`
  ).join('');

  return `${cmm.competitor_overview ? `<div class="callout-box callout-surface" style="margin-bottom:16px">${esc(cmm.competitor_overview)}</div>` : ''}
<div class="r-grid-2">${cards}</div>`;
}

export function renderConversionArchitecture(car) {
  const assessments = [
    ['Website Assessment', car.website_assessment],
    ['Landing Page', car.landing_page_assessment],
    ['Lead Capture', car.lead_capture_assessment],
    ['Contact Path', car.contact_path_assessment],
  ].filter(([, v]) => v).map(([k, v]) =>
    `<div class="r-card r-card--plain break-avoid"><div class="r-card-label">${esc(k)}</div><div class="r-card-val">${esc(v)}</div></div>`
  ).join('');

  const issues = [
    { label: 'Friction Points', cls: 'r-card--red', items: car.conversion_friction_points },
    { label: 'Trust Gaps', cls: 'r-card--amber', items: car.trust_gaps },
    { label: 'CTA Weaknesses', cls: 'r-card--amber', items: car.cta_weaknesses },
    { label: 'Opportunities', cls: 'r-card--green', items: car.conversion_opportunities },
  ].filter(i => i.items?.length).map(i =>
    `<div class="r-card ${i.cls} break-avoid"><div class="r-card-label">${esc(i.label)}</div><ul class="r-card-list">${safeList(i.items)}</ul></div>`
  ).join('');

  return `<div class="r-grid-2" style="margin-bottom:14px">${assessments}</div>
<div class="r-grid-2">${issues}</div>`;
}

export function renderSWOT(swot) {
  return `<div class="r-grid-2 swot-grid">
  <div class="r-card r-card--green break-avoid"><div class="r-card-label swot-label">Strengths</div><ul class="r-card-list">${safeList(swot.strengths)}</ul></div>
  <div class="r-card r-card--amber break-avoid"><div class="r-card-label swot-label">Weaknesses</div><ul class="r-card-list">${safeList(swot.weaknesses)}</ul></div>
  <div class="r-card r-card--blue break-avoid"><div class="r-card-label swot-label">Opportunities</div><ul class="r-card-list">${safeList(swot.opportunities)}</ul></div>
  <div class="r-card r-card--red break-avoid"><div class="r-card-label swot-label">Threats</div><ul class="r-card-list">${safeList(swot.threats)}</ul></div>
</div>`;
}

export function renderGrowthForecast(gf) {
  const cards = [
    ['Visibility', gf.visibility_opportunities],
    ['Authority', gf.authority_opportunities],
    ['Conversion', gf.conversion_opportunities],
    ['Audience Growth', gf.audience_growth_opportunities],
  ].filter(([, v]) => v?.length).map(([k, v]) =>
    `<div class="r-card r-card--plain break-avoid"><div class="r-card-label">${esc(k)}</div><ul class="r-card-list">${safeList(v)}</ul></div>`
  ).join('');

  return `<div class="r-grid-2">${cards}</div>
${gf.assumptions ? `<div class="callout-box callout-slate" style="margin-top:12px">Assumptions: ${esc(gf.assumptions)}</div>` : ''}`;
}

export function renderAuditConfidence(ac) {
  return `${ac.data_quality ? `<div class="callout-box callout-surface" style="margin-bottom:16px">${esc(ac.data_quality)}</div>` : ''}
<div class="r-grid-3">
  ${ac.observed_findings?.length ? `<div class="r-card r-card--green break-avoid"><div class="r-card-label">Observed</div><ul class="r-card-list">${safeList(ac.observed_findings)}</ul></div>` : ''}
  ${ac.inferred_findings?.length ? `<div class="r-card r-card--blue break-avoid"><div class="r-card-label">Inferred</div><ul class="r-card-list">${safeList(ac.inferred_findings)}</ul></div>` : ''}
  ${ac.estimated_findings?.length ? `<div class="r-card r-card--amber break-avoid"><div class="r-card-label">Estimated</div><ul class="r-card-list">${safeList(ac.estimated_findings)}</ul></div>` : ''}
</div>
${ac.limitations ? `<div class="callout-box callout-slate" style="margin-top:12px"><strong>Limitations:</strong> ${esc(ac.limitations)}</div>` : ''}
<div class="ac-legend">
  <span class="ac-leg-item"><strong>Observed</strong> — confirmed from crawled data</span>
  <span class="ac-leg-item"><strong>Inferred</strong> — derived from available signals</span>
  <span class="ac-leg-item"><strong>Estimated</strong> — extrapolated from industry patterns</span>
</div>`;
}
