name = "mypilotpost-api"
main = "src/server.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

[vars]
BASE_URL = "https://api.mypilotpost.com"
ENVIRONMENT = "production"
API_VERSION = "v1"
GOOGLE_CLIENT_ID = "626126586204-kpm1sra6t8488t47an9m4ta030615c8s.apps.googleusercontent.com"
DROPBOX_CLIENT_ID = "yt1hvspft36igsa"
LINKEDIN_CLIENT_ID = "771mxvzllsxgrp"

[[d1_databases]]
binding = "mypilotpost"
database_name = "mypilotpost"
database_id = "e8075c44-5b6a-40c4-91cb-ebaef3da2a82"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "mypilotpost-media"
preview_bucket_name = "mypilotpost-media-preview"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "8ec7110460ae435a86e33999c115eec3"
preview_id = "af2c556897934423bb0da6d8ba106cac"

[triggers]
crons = ["* * * * *", "0 3 * * *"]

[observability]
enabled = true
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "SupportChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["SupportChatRoom"]
