export const INDUSTRY_LIST = [
  "Accounting",
  "Aerospace & Defense",
  "Agriculture",
  "AI & Machine Learning",
  "Alternative Medicine",
  "Architecture & Design",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Baby & Children Products",
  "Banking",
  "Beauty",
  "Beverages (Alcoholic)",
  "Beverages (Non-Alcoholic)",
  "Biotechnology",
  "Book Publishing",
  "Business Supplies & Equipment",
  "Chemical Industry",
  "Chiropractic Care",
  "Clean Energy & Solar",
  "Commercial Printing",
  "Computer Hardware",
  "Computer Networking",
  "Construction",
  "Consulting",
  "Consumer Electronics",
  "Cosmetics & Personal Care",
  "Coworking & Shared Spaces",
  "Cybersecurity",
  "Dental",
  "Design Services",
  "Digital Media",
  "E-commerce",
  "Ecommerce",
  "Education",
  "Energy & Utilities",
  "Environmental Services",
  "Events",
  "Executive Search",
  "Facility Management",
  "Fashion",
  "Finance",
  "Financial Advisory",
  "Fine Art & Galleries",
  "Fintech",
  "Fitness",
  "Fitness & Wellness",
  "Food",
  "Food & Beverage",
  "Food & Beverage Production",
  "Furniture & Home Decor",
  "Gaming & Esports",
  "General Business",
  "General Contracting",
  "Graphic Design",
  "Green Tech",
  "Grocery & Supermarkets",
  "Hardware & Tools",
  "Healthcare",
  "Home Services",
  "Hospitality",
  "Hotels",
  "Human Resources",
  "Import & Export",
  "Information Technology",
  "Insurance",
  "Interior Design",
  "Investment Banking",
  "IT Consulting",
  "Jewelry & Luxury Goods",
  "Landscaping & Gardening",
  "Legal",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Management Consulting",
  "Manufacturing",
  "Marine & Shipping",
  "Marketing Agency",
  "Media & Entertainment",
  "Medical Devices",
  "Mental Health & Counseling",
  "Mining & Metals",
  "Moving & Storage",
  "Moving Services",
  "Music & Audio Production",
  "Nonprofit",
  "Oil & Gas",
  "Optometry & Eye Care",
  "Organic & Natural Products",
  "Packaging & Containers",
  "Pest Control",
  "Pet Products & Services",
  "Pharmaceuticals",
  "Photography & Videography",
  "Professional Services",
  "Property Management",
  "Public Relations",
  "Real Estate",
  "Real Estate Development",
  "Recruitment",
  "Renewables & Environment",
  "Renewable Energy",
  "Restaurants",
  "Retail",
  "Retail / Fashion",
  "SaaS",
  "SaaS / Software",
  "Software Development",
  "Sports & Recreation",
  "Technology",
  "Telecommunications",
  "Travel",
  "Travel & Hospitality",
  "Transportation & Warehousing",
  "Venture Capital & Private Equity",
  "Veterinary Services",
  "Waste Management",
  "Wholesale",
  "Writing & Editing",
  "Yoga & Mindfulness"
];
